apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-flask
  namespace: demo
spec:
  replicas: 1
  selector:
    matchLabels: { app: hello-flask }
  template:
    metadata:
      labels: { app: hello-flask }
    spec:
      containers:
        - name: app
          image: kousthubsarma/hello-flask:latest
          imagePullPolicy: Always
          ports: [{ containerPort: 8000 }]
          readinessProbe:
            httpGet: { path: /health, port: 8000 }
            initialDelaySeconds: 2
          livenessProbe:
            httpGet: { path: /health, port: 8000 }
            initialDelaySeconds: 5
