apiVersion: v1
kind: Service
metadata:
  name: hello-flask
  namespace: demo
spec:
  selector:
    app: hello-flask
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
  type: ClusterIP
